# Generated by Django 2.2.17 on 2021-03-09 15:03

from django.db import migrations, models
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0010_auto_20210309_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='image_alt',
            field=versatileimagefield.fields.VersatileImageField(blank=True, height_field='image_alt_height', null=True, upload_to='activities/', verbose_name='Image alt', width_field='image_alt_width'),
        ),
        migrations.AddField(
            model_name='activity',
            name='image_alt_height',
            field=models.PositiveIntegerField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='image_alt_width',
            field=models.PositiveIntegerField(editable=False, null=True),
        ),
    ]
