# Generated by Django 2.2.17 on 2021-03-09 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0011_auto_20210309_1703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='image_alt',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='image_alt_height',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='image_alt_width',
        ),
        migrations.RemoveField(
            model_name='presenter',
            name='image_alt',
        ),
        migrations.RemoveField(
            model_name='presenter',
            name='image_alt_height',
        ),
        migrations.RemoveField(
            model_name='presenter',
            name='image_alt_width',
        ),
    ]
