# Generated by Django 2.2.17 on 2021-04-30 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0006_auto_20200302_0614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='team',
            field=models.CharField(choices=[('experience', 'Experience'), ('it', 'IT'), ('fundraising', 'Fundraising'), ('graphics', 'Graphics'), ('media', 'Media'), ('speakers', 'Speakers'), ('venue-production', 'Venue & Production'), ('photography', 'Photography')], max_length=16),
        ),
    ]
