# Generated by Django 2.2.17 on 2021-03-24 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0004_auto_20200302_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='career_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
