# Generated by Django 2.2.17 on 2021-04-16 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0005_partner_career_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='partner_type',
            field=models.CharField(choices=[('PS', 'Platinum Sponsors'), ('GS', 'Grand Sponsors'), ('GCS', 'Grand Carrier Sponsors'), ('GHS', 'Grand Hospitality Sponsors'), ('SPO', 'Sponsors'), ('SUP', 'Supporters'), ('MP', 'Media Partners'), ('CP', 'Community Partners')], max_length=3),
        ),
    ]
