# Generated by Django 2.2.17 on 2021-04-30 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0006_auto_20210416_0313'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnertranslation',
            name='description',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='description'),
        ),
    ]
